### ISSUE TITLE
An unexpected error has been raised. Looks like there's something wrong at our end.

### ISSUE THREAD

**Issue by alexanderkladov** [simplifycom/woocommerce-simplify-payment-gateway-plugin#30] opened 2020-08-10 05:48 UTC
Hi,

We had a few clients report a payment failure at checkout, where they saw the following notice displayed on the website:

> An unexpected error has been raised.  Looks like there's something wrong at our end.

Can you please let me know what might have caused this?

Regards,
Alex

**Comment by JohnbConneely** [comment] 2020-09-01 09:03
Hey @alexanderkladov, Apologies for the delay in this one. We are working on some translation issues around special characters and hope to have a solution out soon. It's likely that this is the cause of this issue.

**Comment by JohnbConneely** [comment] 2020-09-04 14:50
Hey @alexanderkladov we have released a new version of the plugin. Please check if it solves your issue.

If your issue persists, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.

**Closed by JohnbConneely** 2020-09-04 14:50 UTC
